- Monitoring:
    - Logs (Dozzle):
        href: http://192.168.1.31:8080
        icon: dozzle.png
    - Grafana:
        href: http://192.168.1.31:3002
        icon: grafana.png
    - Prometheus:
        href: http://192.168.1.31:9090
        icon: prometheus.png
    - Uptime Kuma:
        href: http://192.168.1.31:3001
        icon: uptime-kuma.png

- Media:
    - Audiobookshelf:
        href: http://192.168.1.31:13378
        icon: audiobookshelf.png
    - Kavita:
        href: http://192.168.1.31:5000
        icon: kavita.png
    - Plex:
        href: http://192.168.1.31:32400/web
        icon: plex.png

- Utilities:
    - FileBrowser:
        href: http://192.168.1.31:8082
        icon: filebrowser.png
    - Playit.gg:
        icon: playit.png
    - Watchtower:
        icon: watchtower.png