- Media:
    - Plex:
        icon: plex.png
        href: http://192.168.1.31:32400/web
  #      widget:
  #        type: plex
  #        url: http://192.168.1.31:32400
  #        key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"

    - Audiobookshelf:
        icon: audiobookshelf.png
        href: http://192.168.1.31:13378
        widget:
          type: audiobookshelf
          url: http://192.168.1.31:13378
          key: "{{HOMEPAGE_VAR_AUDIOBOOKSHELF_KEY}}"

    - Kavita:
        icon: kavita.png
        href: http://192.168.1.31:5000
        widget:
          type: kavita
          url: http://192.168.1.31:5000
          username: "{{HOMEPAGE_VAR_KAVITA_USER}}"
          password: "{{HOMEPAGE_VAR_KAVITA_PASSWORD}}"

- Monitoring:
    - Grafana:
        icon: grafana.png
        href: http://192.168.1.31:3002
        widget:
          type: grafana
          url: http://192.168.1.31:3002
          username: "{{HOMEPAGE_VAR_GRAFANA_USER}}"
          password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"

    - Prometheus:
        icon: prometheus.png
        href: http://192.168.1.31:9090
        widget:
          type: prometheus
          url: http://192.168.1.31:9090

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://192.168.1.31:3001
        widget:
          type: uptimekuma
          url: http://192.168.1.31:3001
          slug: default

    - Logs (Dozzle):
        icon: dozzle.png
        href: http://192.168.1.31:8080

- Infrastructure:
    - Docker:
        icon: docker.png
        widget:
          type: docker
          url: /var/run/docker.sock

    - Watchtower:
        icon: watchtower.png
        widget:
          type: watchtower
          url: /var/run/docker.sock

    - FileBrowser:
        icon: filebrowser.png
        href: http://192.168.1.31:8082

    - AdGuard Home:
        icon: adguard-home.png
        href: http://192.168.1.31:80
  #      widget:
  #        type: adguard
  #        url: http://192.168.1.31:80
  #        username: "{{HOMEPAGE_VAR_ADGUARD_USER}}"
  #        password: "{{HOMEPAGE_VAR_ADGUARD_PASSWORD}}"

    - Playit.gg:
        icon: playit.png


